[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.26.0",
    "pyarrow>=19.0.1",
    "svg-py>=1.6.0",
]
